"""
Orchestrates: noisy OCR text -> clean medicine name/batch details -> recall
lookup (vector DB first, live web search fallback) -> final structured answer.
"""

import json
import ast
import re
from decouple import config
from google import genai
from google.genai import types

from vector_store import search_recalled_db

GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-3.5-flash")
GEMINI_FALLBACK_MODELS = [
    model.strip()
    for model in config(
        "GEMINI_FALLBACK_MODELS",
        default="gemini-2.5-flash,gemini-2.5-flash-lite",
    ).split(",")
    if model.strip()
]
ENABLE_WEB_SEARCH = config("ENABLE_WEB_SEARCH", default=False, cast=bool)
ENABLE_LLM_IDENTITY = config("ENABLE_LLM_IDENTITY", default=False, cast=bool)
ENABLE_LLM_SUMMARY = config("ENABLE_LLM_SUMMARY", default=False, cast=bool)

_web_search_available = True
_client = None

DISCLAIMER = (
    "This information is generated by an AI system and may be incomplete or "
    "inaccurate. It is not medical advice. Always consult a licensed medical "
    "practitioner or pharmacist before taking, stopping, or making any "
    "decisions about a medicine."
)


def _get_client():
    global _client
    print(f"API KEY: {config('GEMINI_API_KEY')}")
    if _client is None:
        _client = genai.Client(api_key=config("GEMINI_API_KEY"))
    return _client


def _gemini_models_to_try() -> list[str]:
    models = []
    for model in [GEMINI_MODEL, *GEMINI_FALLBACK_MODELS]:
        if model and model not in models:
            models.append(model)
    return models


def _generate_with_model_fallback(contents, config):
    last_error = None
    for model in _gemini_models_to_try():
        try:
            return _get_client().models.generate_content(
                model=model,
                contents=contents,
                config=config,
            )
        except Exception as e:
            last_error = e
            print(f"[llm] Gemini model {model} failed: {e}")
            if "503" not in str(e) and "UNAVAILABLE" not in str(e):
                break
    raise last_error


def _clean_loose_value(value: str):
    value = value.strip().rstrip(",").strip()
    lower_value = value.lower()

    if lower_value in {"none", "null"}:
        return None
    if lower_value == "true":
        return True
    if lower_value == "false":
        return False

    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        value = value[1:-1]
    elif value.startswith(("'", '"')):
        value = value[1:]
    elif value.endswith(("'", '"')):
        value = value[:-1]

    return " ".join(value.split())


def _parse_loose_object(text: str) -> dict:
    """Parse imperfect model dicts such as single quotes or broken strings."""
    start = text.find("{")
    end = text.rfind("}")
    body = text[start + 1 : end] if start != -1 and end != -1 and end > start else text

    pattern = re.compile(
        r"""["']?([A-Za-z_][A-Za-z0-9_]*)["']?\s*:\s*(.*?)"""
        r"""(?=,\s*["']?[A-Za-z_][A-Za-z0-9_]*["']?\s*:|\n\s*["']?[A-Za-z_][A-Za-z0-9_]*["']?\s*:|$)""",
        re.DOTALL,
    )
    parsed = {
        key: _clean_loose_value(value)
        for key, value in pattern.findall(body)
        if value.strip()
    }
    if not parsed:
        raise ValueError("Model response did not contain parseable key/value pairs")
    return parsed


def _parse_json_response(text: str) -> dict:
    """Parse a model JSON response, tolerating common markdown wrappers."""
    text = (text or "").strip()
    if not text:
        raise ValueError("Empty model response")

    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    start = text.find("{")
    end = text.rfind("}")
    json_text = text[start : end + 1] if start != -1 and end != -1 and end > start else text

    try:
        return json.loads(json_text)
    except json.JSONDecodeError:
        try:
            parsed = ast.literal_eval(json_text)
            if isinstance(parsed, dict):
                return parsed
        except (SyntaxError, ValueError):
            return _parse_loose_object(json_text)
        raise ValueError("Model response was not a JSON object")


def _clean_ocr_line(line: str) -> str:
    line = re.sub(r"[^A-Za-z0-9+/%().,\- ]+", " ", line)
    line = re.sub(r"\s+", " ", line).strip(" .,-")
    return line


def _is_noise_line(line: str) -> bool:
    lowered = line.lower()
    noise_terms = {
        "mrp",
        "price",
        "license",
        "licence",
        "address",
        "customer",
        "warning",
        "caution",
        "store",
        "temperature",
        "schedule",
        "dosage",
        "barcode",
    }
    if any(term in lowered for term in noise_terms):
        return True
    letters = sum(ch.isalpha() for ch in line)
    digits = sum(ch.isdigit() for ch in line)
    return letters < 3 and digits < 3


def _normalize_batch_number(batch_number: str) -> str:
    batch_number = (batch_number or "").upper()
    return re.sub(r"[^A-Z0-9/-]", "", batch_number)


def _looks_like_batch_candidate(value: str) -> bool:
    value = _normalize_batch_number(value)
    if not 3 <= len(value) <= 16:
        return False
    digit_count = sum(ch.isdigit() for ch in value)
    if digit_count == 0:
        return False
    if len(value) <= 3 and digit_count < 2:
        return False
    if value.isdigit() and len(value) < 4:
        return False
    rejected = {
        "400MG",
        "31UA",
        "31UA2013",
        "31/UA",
        "ML31UA2013",
        "9330155",
        "2013",
        "2024",
        "2025",
        "249403",
        "400013",
    }
    if value in rejected:
        return False
    date_terms = (
        "MFG", "MFD", "EXP", "EXPIRY", "DATE",
        "JAN", "FEB", "MAR", "APR", "MAY", "JUN",
        "JUL", "AUG", "SEP", "OCT", "NOV", "DEC",
    )
    if any(term in value for term in date_terms):
        return False
    if re.search(r"\d+M+G", value):
        return False
    if "UA" in value and re.search(r"20\d{2}$", value):
        return False
    if value.startswith("ML"):
        return False
    if value.startswith(("400013", "249403")):
        return False
    if "ENDEX" in value or value.startswith(("BENDEX", "ALBENDAZOLE")):
        return False
    return True


def _batch_from_unlabeled_stamp(lines: list[str], normalized_text: str) -> str | None:
    """Some strips stamp the batch immediately before MFG/EXP without a clear
    Batch/B.No label. Use only tight stamp-neighborhood candidates to avoid
    picking dosage, license, MRP, or address numbers."""
    stamp_context = re.compile(
        r"\b([A-Z]?[A-Z0-9][A-Z0-9./-]{2,15})\s+MFG\.?\s*DATE\b",
        re.IGNORECASE,
    )
    match = stamp_context.search(normalized_text)
    if match and _looks_like_batch_candidate(match.group(1)):
        return _normalize_batch_number(match.group(1))

    for idx, line in enumerate(lines):
        if not re.search(r"\b(MFG|MFD|EXP|EXPIRY)\b", line, re.IGNORECASE):
            continue
        candidates = []
        candidates.extend(re.findall(r"\b[A-Z]?[A-Z0-9][A-Z0-9./-]{2,15}\b", line, re.IGNORECASE))
        if idx > 0:
            candidates.extend(re.findall(r"\b[A-Z]?[A-Z0-9][A-Z0-9./-]{2,15}\b", lines[idx - 1], re.IGNORECASE))
        for candidate in candidates:
            if _looks_like_batch_candidate(candidate):
                return _normalize_batch_number(candidate)

    if re.search(r"\b(MFG|MFD|EXP|EXPIRY)\b", normalized_text, re.IGNORECASE):
        isolated_candidates = []
        for line in lines:
            if re.search(r"\b(MFG|MFD|EXP|EXPIRY|ML|M\.L|MRP|RS|MG)\b", line, re.IGNORECASE):
                continue
            if "." not in line:
                continue
            if not re.fullmatch(r"[A-Z]?[A-Z0-9][A-Z0-9./-]{2,15}", line, re.IGNORECASE):
                continue
            if not re.search(r"[A-Z]", line, re.IGNORECASE):
                continue
            if _looks_like_batch_candidate(line):
                isolated_candidates.append(_normalize_batch_number(line))
        if isolated_candidates:
            return isolated_candidates[0]
    return None


def _identity_from_ocr_text(raw_ocr_text: str) -> dict:
    lines = [_clean_ocr_line(line) for line in raw_ocr_text.splitlines()]
    lines = [line for line in lines if line and not _is_noise_line(line)]
    normalized_text = _clean_ocr_line(raw_ocr_text)
    normalized_lower = normalized_text.lower()

    # Regex for batch number
    batch_pattern = re.compile(
        r"\b(?:b\.?\s*no\.?|batch(?:\s*no\.?)?|lot(?:\s*no\.?)?|b/n)\s*[:.-]?\s*([a-z0-9\-/]+)\b",
        re.IGNORECASE
    )
    batch_match = batch_pattern.search(normalized_lower)
    batch_number = None
    if batch_match:
        start_idx = normalized_lower.find(batch_match.group(1))
        if start_idx != -1:
            batch_number = _normalize_batch_number(
                normalized_text[start_idx:start_idx+len(batch_match.group(1))].strip()
            )
        else:
            batch_number = _normalize_batch_number(batch_match.group(1))
        if not _looks_like_batch_candidate(batch_number):
            batch_number = None

    if not batch_number:
        batch_number = _batch_from_unlabeled_stamp(lines, normalized_text)

    # Regex for mfg / expiry dates
    date_pattern = re.compile(
        r"\b(mfg|exp|expiry)\b.+(0[1-9]|1[0-2])[-/](20[2-3][0-9]|[2-3][0-9])\b",
        re.IGNORECASE
    )
    dates = date_pattern.findall(normalized_lower)
    mfg_date = None
    expiry_date = None
    for match in dates:
        lbl, mm, yy = match
        date_str = f"{mm}/{yy}"
        if "mfg" in lbl:
            mfg_date = date_str
        else:
            expiry_date = date_str

    brand_name = None
    generic_name = None
    if lines:
        # Simple heuristic: lines containing dosage are generic composition, others are brand
        composition_terms = ("contains", "composition", "each", "equivalent", "mg", "ml", "ip", "usp")
        generic_line = next((line for line in lines if any(term in line.lower() for term in composition_terms)), None)
        brand_line = next((line for line in lines if line != generic_line), lines[0])

        brand_name = brand_line
        generic_name = generic_line

    search_query = " ".join(part for part in (brand_name, f"batch {batch_number}" if batch_number else "") if part)

    return {
        "brand_name": brand_name,
        "generic_name": generic_name,
        "batch_number": batch_number,
        "manufacturer": None,
        "mfg_date": mfg_date,
        "expiry_date": expiry_date,
        "search_query": search_query or normalized_text[:200],
        "confidence": "medium" if batch_number else "low",
    }


def extract_medicine_identity(raw_ocr_text: str) -> dict:
    """Cleans noisy OCR text into structured details including batch/lot number
    and manufacturer details."""
    if not ENABLE_LLM_IDENTITY:
        return _identity_from_ocr_text(raw_ocr_text)

    prompt = f"""You are given messy OCR text extracted from the back of a medicine
strip/box. It may contain typos, broken words, batch numbers, dates, and
manufacturer details mixed in.

OCR TEXT:
---
{raw_ocr_text}
---

Extract the structured medicine identity details. Be very careful to identify the batch/lot number, manufacturer name, manufacturing date, and expiry date if present.

Return ONLY a JSON object (no markdown fences, no preamble) with this shape:
{{
  "brand_name": "<best guess of brand name, or null>",
  "generic_name": "<best guess of active ingredient(s)/generic/composition, or null>",
  "batch_number": "<exact batch or lot number found, e.g., 'MX8739A', 'DL98762', or null>",
  "manufacturer": "<best guess of manufacturing company name, or null>",
  "mfg_date": "<manufacturing date, e.g., '05/2024' or null>",
  "expiry_date": "<expiry date, e.g., '04/2026' or null>",
  "search_query": "<a clean search string combining medicine name and batch number, best for looking up recall status>",
  "confidence": "<high|medium|low>"
}}"""

    try:
        resp = _generate_with_model_fallback(
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=1000,
                response_mime_type="application/json",
                thinking_config=types.ThinkingConfig(thinking_budget=0),
            ),
        )
        return _parse_json_response(resp.text)
    except Exception as e:
        print(f"[llm] LLM identity extraction failed, using local OCR identity: {e}")
        return _identity_from_ocr_text(raw_ocr_text)


def _answer_from_best_db_match(identity: dict, matches: list[dict]) -> dict:
    best_match = matches[0] if matches else {}
    medicine_name = (
        best_match.get("medicine_name")
        or identity.get("brand_name")
        or identity.get("generic_name")
        or "Unknown Medicine"
    )
    batch_number = best_match.get("batch_number") or identity.get("batch_number")
    recall_date = best_match.get("recall_date")
    agency = best_match.get("recalling_agency")
    reason = best_match.get("recall_reason")
    status_label = best_match.get("recall_status") or "NSQ"
    if str(status_label).strip().lower() in {"recalled", "nsq / recalled"}:
        status_label = "NSQ"

    date_phrase = f" reported in {recall_date}" if recall_date else ""
    agency_phrase = f" by {agency}" if agency else ""

    return {
        "medicine_name": medicine_name,
        "batch_number": batch_number,
        "manufacturer": best_match.get("manufacturer") or identity.get("manufacturer"),
        "is_recalled": True,
        "recall_date": recall_date,
        "recall_reason": reason,
        "recalling_agency": agency,
        "recall_class": best_match.get("recall_class"),
        "recommendation": best_match.get("recommendation"),
        "mfg_date": best_match.get("mfg_date"),
        "expiry_date": best_match.get("expiry_date"),
        "reporting_source": best_match.get("reporting_source"),
        "reporting_lab": best_match.get("reporting_lab"),
        "status_summary": (
            f"{status_label.upper()}: Batch {batch_number} of {medicine_name} "
            f"is in NSQ{date_phrase}{agency_phrase}. Reason: {reason}"
        ),
        "general_info": (
            f"This batch was manufactured by {best_match.get('manufacturer')}. "
            f"Classification: {best_match.get('recall_class') or status_label}."
        ),
        "source": "internal_database",
    }


def _answer_from_known_safe_db_match(identity: dict, matches: list[dict]) -> dict:
    best_match = matches[0] if matches else {}
    medicine_name = (
        best_match.get("medicine_name")
        or identity.get("brand_name")
        or identity.get("generic_name")
        or "Unknown Medicine"
    )
    batch_number = best_match.get("batch_number") or identity.get("batch_number")

    return {
        "medicine_name": medicine_name,
        "batch_number": batch_number,
        "manufacturer": best_match.get("manufacturer") or identity.get("manufacturer"),
        "is_recalled": False,
        "recall_date": None,
        "recall_reason": None,
        "recalling_agency": best_match.get("recalling_agency") or "Internal Database",
        "recall_class": None,
        "recommendation": best_match.get("recommendation")
        or "No recall action required based on the internal database.",
        "status_summary": (
            f"Not in NSQ: Batch {batch_number} of {medicine_name} was found in "
            "the internal database and is marked Not in NSQ."
        ),
        "general_info": (
            f"This batch is listed for {best_match.get('manufacturer')}. "
            "No recall reason or recall date is recorded for it."
        ),
        "source": "internal_database",
    }


def _answer_from_vector_matches(identity: dict, matches: list[dict]) -> dict:
    if not ENABLE_LLM_SUMMARY:
        return _answer_from_best_db_match(identity, matches)

    prompt = f"""A user scanned a medicine. Extracted identity: {json.dumps(identity)}.

Our internal database found these potentially matching recalled medicine batch records:
{json.dumps(matches, indent=2)}

Using ONLY this data plus your general pharmacology knowledge for the "general
info" section, respond with ONLY a JSON object (no markdown fences):
{{
  "medicine_name": "<best identified name>",
  "batch_number": "<exact batch number>",
  "manufacturer": "<manufacturer name>",
  "is_recalled": true,
  "recall_date": "<recall date>",
  "recall_reason": "<1-2 sentence recall reason>",
  "recalling_agency": "<regulatory agency>",
  "recall_class": "<recall class, e.g. Class I, Class II>",
  "recommendation": "<recommendation for the patient>",
  "status_summary": "<1-2 sentence plain-language summary of recall status and reason>",
  "general_info": "<2-4 sentence general info on what this medicine/class is typically used for>",
  "source": "internal_database"
}}"""

    try:
        resp = _generate_with_model_fallback(
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=1000,
                response_mime_type="application/json",
                thinking_config=types.ThinkingConfig(thinking_budget=0),
            ),
        )
        return _parse_json_response(resp.text)
    except Exception as e:
        print(f"[llm] Vector-match summarization failed, using raw DB match: {e}")
        return _answer_from_best_db_match(identity, matches)


def _answer_without_web_search(identity: dict) -> dict:
    medicine_name = identity.get("brand_name") or identity.get("generic_name") or "Unknown Medicine"
    batch_number = identity.get("batch_number")

    source = "local_database_no_match"
    general_info = "Checked against local database only. (Live web search is disabled.)"
    if ENABLE_WEB_SEARCH and not _web_search_available:
        source = "web_search_unavailable"
        general_info = (
            "Checked against local database only because live web search is currently unavailable. "
            "Please try again later."
        )

    base = {
        "medicine_name": medicine_name,
        "batch_number": batch_number,
        "manufacturer": identity.get("manufacturer"),
        "is_recalled": False,
        "recall_date": None,
        "recall_reason": None,
        "recalling_agency": None,
        "recall_class": None,
        "recommendation": "No action required. This batch is not listed in the NSQ database.",
        "status_summary": "Not in NSQ: This batch was not found in our NSQ database.",
        "general_info": general_info,
        "source": source,
    }

    if not ENABLE_LLM_SUMMARY or not medicine_name or medicine_name == "Unknown Medicine":
        return base

    prompt = f"""A user scanned a medicine batch that is NOT in our recalled database.
Identity extracted from the packaging: {json.dumps(identity)}.

Using your general pharmacology knowledge, respond with ONLY a JSON object
(no markdown fences):
{{
  "general_info": "<2-4 sentences: what this medicine/active ingredient is, its drug class, and what it is commonly used to treat. If you are unsure what the medicine is, say so plainly.>"
}}"""

    try:
        resp = _generate_with_model_fallback(
            contents=prompt,
            config=types.GenerateContentConfig(
                max_output_tokens=1000,
                response_mime_type="application/json",
                thinking_config=types.ThinkingConfig(thinking_budget=0),
            ),
        )
        info = _parse_json_response(resp.text).get("general_info", "")
        if info:
            base["general_info"] = info
    except Exception as e:
        print(f"[llm] General-info lookup failed: {e}")

    return base


def _answer_without_batch_number(identity: dict) -> dict:
    medicine_name = identity.get("brand_name") or identity.get("generic_name") or "Unknown Medicine"
    return {
        "medicine_name": medicine_name,
        "batch_number": None,
        "manufacturer": identity.get("manufacturer"),
        "is_recalled": None,
        "recall_date": None,
        "recall_reason": None,
        "recalling_agency": None,
        "recall_class": None,
        "recommendation": (
            "Upload a clearer close-up of the batch/MFG/EXP stamp or type the "
            "batch number manually, then run the check again."
        ),
        "status_summary": (
            "Batch number was not detected, so this scan could not verify a "
            "specific medicine batch."
        ),
        "general_info": (
            "OCR may miss purple or embossed batch stamps on reflective foil, "
            "especially when the photo is rotated, blurred, cropped, or affected by glare."
        ),
        "source": "batch_not_detected",
    }


def _answer_from_web_search(identity: dict) -> dict:
    """Fallback path: nothing in the vector DB, so ask Gemini to research it live
    using Google Search grounding."""
    medicine_name = identity.get("brand_name") or identity.get("generic_name") or "Unknown Medicine"
    batch_number = identity.get("batch_number")
    manufacturer = identity.get("manufacturer") or ""

    query = f"{medicine_name} {f'batch {batch_number}' if batch_number else ''} {manufacturer} recall"

    prompt = f"""Research whether the medicine "{medicine_name}" (batch: {batch_number},
manufacturer: {manufacturer}) has been recalled by health authorities (such as US FDA, CDSCO, etc.). 
Use web search to check for active product recall alerts related to this medicine and batch.

If you find a recall matching this batch (or if all batches of this product are recalled), return the recall details.
If no recall matches this batch/product, state that it is not recalled.

Respond with ONLY a JSON object as your final message (no markdown fences, no extra commentary):
{{
  "medicine_name": "<best identified name>",
  "batch_number": "<batch number checked>",
  "manufacturer": "<manufacturer checked, or null>",
  "is_recalled": true|false|null,
  "recall_date": "<date of recall (YYYY-MM-DD or Month YYYY) if recalled, or null>",
  "recall_reason": "<1-2 sentence description of the recall reason if recalled, or null>",
  "recalling_agency": "<regulatory agency e.g. 'US FDA', 'CDSCO', or null>",
  "recall_class": "<recall classification e.g. 'Class I', 'Class II', or null>",
  "recommendation": "<advisory warning/recommendation for patient if recalled, or null>",
  "status_summary": "<1-2 sentence summary of recall status>",
  "general_info": "<1-2 sentences context from the search results, e.g. date of search validation>",
  "source": "web_search"
}}"""

    resp = _generate_with_model_fallback(
        contents=prompt,
        config=types.GenerateContentConfig(
            max_output_tokens=3000,
            tools=[types.Tool(google_search=types.GoogleSearch())],
            thinking_config=types.ThinkingConfig(thinking_budget=0),
        ),
    )
    final_text = (resp.text or "{}").strip()

    try:
        parsed = _parse_json_response(final_text)
        if parsed.get("is_recalled") == "true" or parsed.get("is_recalled") is True:
            parsed["is_recalled"] = True
        elif parsed.get("is_recalled") == "false" or parsed.get("is_recalled") is False:
            parsed["is_recalled"] = False
        return parsed
    except Exception as e:
        print(f"[llm] Parsing web search failed: {e}")
        return {
            "medicine_name": medicine_name,
            "batch_number": batch_number,
            "manufacturer": manufacturer,
            "is_recalled": None,
            "recall_date": None,
            "recall_reason": None,
            "recalling_agency": None,
            "recall_class": None,
            "recommendation": "Please verify this batch status manually on the official FDA or CDSCO websites.",
            "status_summary": "Web search ran but the result could not be parsed reliably.",
            "general_info": "An error occurred parsing the search results.",
            "source": "web_search",
        }


def analyze_medicine(raw_ocr_text: str, manual_batch: str = "", manual_med: str = "") -> dict:
    """Full pipeline: identity extraction -> vector DB lookup -> web fallback."""
    global _web_search_available
    identity = extract_medicine_identity(raw_ocr_text)
    print(f"[llm] Extracted identity: {identity}")
    # Merge manual inputs if provided
    manual_batch = (manual_batch or "").strip()
    manual_med = (manual_med or "").strip()

    if manual_batch:
        identity["batch_number"] = manual_batch
    if manual_med:
        identity["brand_name"] = manual_med

    # Recalculate search query if manual inputs changed things
    if manual_batch or manual_med:
        query_parts = []
        if identity.get("brand_name"):
            query_parts.append(identity["brand_name"])
        if identity.get("batch_number"):
            query_parts.append(f"batch {identity['batch_number']}")
        identity["search_query"] = " ".join(query_parts).strip()

    batch = identity.get("batch_number") or ""
    med = identity.get("brand_name") or identity.get("generic_name") or ""

    if not batch:
        result = _answer_without_batch_number(identity)
        result["identity"] = identity
        result["disclaimer"] = DISCLAIMER
        return result

    matches = search_recalled_db(batch_number=batch, medicine_name=med)

    recalled_matches = [match for match in matches if match.get("is_recalled") is True]

    if recalled_matches:
        result = _answer_from_vector_matches(identity, recalled_matches)
    elif matches:
        result = _answer_from_known_safe_db_match(identity, matches)
    elif ENABLE_WEB_SEARCH and _web_search_available:
        try:
            result = _answer_from_web_search(identity)
        except Exception as e:
            print(f"[llm] Web search fallback failed: {e}")
            if "RESOURCE_EXHAUSTED" in str(e) or "quota" in str(e).lower():
                _web_search_available = False
                print("[llm] Disabling further web search attempts until restart due to quota limits.")
            result = _answer_without_web_search(identity)
    else:
        result = _answer_without_web_search(identity)

    result["identity"] = identity
    result["disclaimer"] = DISCLAIMER
    return result
